In [2]:
import numpy as np
import random

# buat data randaom dengan ukuran 10.000.000

size = 10_000_000

# Data Gaji Karyawan 
gaji_karyawan = [random.randint(5000000, 15000000) for _ in range (size)]


# data array gaji 
array_gaji = np.array(gaji_karyawan)



In [81]:
%%timeit
# Mencari rata rata gaji denagn python

avg_gaji = sum(gaji_karyawan) / len(gaji_karyawan)

73.3 ms ± 263 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [82]:
%%timeit

avg_gaji1 = np.mean(array_gaji)

6.12 ms ± 56.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
# Mmembuat array 1D dengan function np.array()

list_1D = [1,2,3,4,5]
array_1D = np.array(list_1D)
print (f"Array 1D: {array_1D}")


# array 2D 

list_2D = [[1,2,3,4], [2,3,5,3]]
array_2D = np.array(list_2D)
print(f"Array 2D = \n{array_2D}")

# array 3D 

list_3D = [[[1,2,3,4], [2,3,5,3]], [[3,2,4,5], [3,2,5,2]]]
array_3D = np.array(list_3D)
print(f"Array 3D = \n {array_3D}")

Array 1D: [1 2 3 4 5]
Array 2D = 
[[1 2 3 4]
 [2 3 5 3]]
Array 3D = 
 [[[1 2 3 4]
  [2 3 5 3]]

 [[3 2 4 5]
  [3 2 5 2]]]


In [21]:
list_1D = [1,2,3,4,5]
array_1D = np.array(list_1D, dtype=np.int32)
print (f"Array 1D: {array_1D}")


array_1D.dtype

Array 1D: [1 2 3 4 5]


dtype('int32')

Membuat array dengan np.arange()

untuk membuat array yang mempunyai rentang tertentu dan langkah tertentu seperti range( ) di python

Sintaks :

np.arange (start , stop ,step , dtype = None)

In [25]:
array_arange = np.arange(0.1 , stop = 50 , step = 5)

print(f"array = {array_arange}")

array = [ 0.1  5.1 10.1 15.1 20.1 25.1 30.1 35.1 40.1 45.1]


Membuat array dengan np.zeros() dan np.ones()

element-element ya menjadi 0 atau satu 

sintaks: 

- np.zeros ( shape , dtype=float)
- np.ones ( shape , dtype=float)


shape: Dimensi array (tuple atau integer )

In [4]:
# membuat array 1D nol

array_zeros = np.zeros(5)
print(f"array 1d nol = {array_zeros}")


array_zeros_2d = np.zeros((2,6), dtype=int)
print(f"array nol 2d = {array_zeros_2d}")

array_zeros_3d = np.zeros((4,6,5), dtype=int)
print(f"array nol 3d = {array_zeros_3d}")

array 1d nol = [0. 0. 0. 0. 0.]
array nol 2d = [[0 0 0 0 0 0]
 [0 0 0 0 0 0]]
array nol 3d = [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


        Mengatur Dimensi Array dengan atribut .reshape() atau .shape
        meratakan array dengan flatten()

In [8]:
array = np.arange(12)
print(f"array asli : {array}")

#mengubah array ke 2D (3x4)

array_2d = array.reshape(3,4)
print(f"array 2d : {array_2d}")


array_3d = array.reshape(2,2,3)
print(f"array 3d : {array_3d}")


array.shape = (6,2)
print(array)

#meratakan array 

array_flatened = array_2d.flatten()
print(f"array 2d jadi 1d : {array_flatened}")


array asli : [ 0  1  2  3  4  5  6  7  8  9 10 11]
array 2d : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array 3d : [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
array 2d jadi 1d : [ 0  1  2  3  4  5  6  7  8  9 10 11]


indexing dan slicing 


index : mengambil elemen tertentu dari array 

slicing : mengambil sebagian elemen array berdasarkan format [start:stop:step]


In [40]:
array_1d = np.array([10,20,30,40,50])


print(f"element pertama : {array_1d[0]}")
print(f"element pertama : {array_1d[-1]}")
print(f"slicing dari element 2 sampai 3  : {array_1d[1:3]}")

array_2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f"Element baris pertama, kolom 2 : {array_2d[2,3]}")
print(f"Slicing baris 1, kolom 1 sampai 3: {array_2d[0,1:3]}")
print(f"Slicing baris 1 dan 2, semua kolom: {array_2d[::,:]}")
print(f"Slicing semua baris,  kolom 1 dan 2 : {array_2d[::,:2]}")

element pertama : 10
element pertama : 50
slicing dari element 2 sampai 3  : [20 30]
Element baris pertama, kolom 2 : 12
Slicing baris 1, kolom 1 sampai 3: [2 3]
Slicing baris 1 dan 2, semua kolom: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Slicing semua baris,  kolom 1 dan 2 : [[ 1  2]
 [ 5  6]
 [ 9 10]]


Mengubah Nilai Element array
numpy mendukung pengubahan nilai elemen secara langsung dengan indeks

In [47]:
array = np.arange(6)
print(f"sebelum array di ubah : {array}")

array[0] = -1
array[-1] = 100

print(f"sesudah array di ubah : {array}")

array[1:3] = [100,200]
print(f"sesudah array di ubah : {array}")

sebelum array di ubah : [0 1 2 3 4 5]
sesudah array di ubah : [ -1   1   2   3   4 100]
sesudah array di ubah : [ -1 100 200   3   4 100]


Operasi matk + - * / 
pada numpy

In [49]:
array = np.arange(5)
print(f"array asli : {array}")

array_add = array + 3 
print(f"array ditambah 3 : {array_add}")

array_sub = array - 2
print(f"array dikurang 2 : {array_sub}")

array_mul = array * 2
print(f"array dikali 2 : {array_mul}")

array_div = array / 2
print(f"array dibagi 2 : {array_div}")

array asli : [0 1 2 3 4]
array ditambah 3 : [3 4 5 6 7]
array dikurang 2 : [-2 -1  0  1  2]
array dikali 2 : [0 2 4 6 8]
array dibagi 2 : [0.  0.5 1.  1.5 2. ]


atribut array 

Numpy menyediakan atribut seperti shape dan size memeriksa dimensi dan jumlah element array 


In [58]:
array = np.array([[1,2,3],[4,5,6]]) 
print(f"array : {array}")

array.shape 
print(f"shape array : {array.shape}")

array.size 
print(f"jumlah elemen array : {array.size}")

array : [[1 2 3]
 [4 5 6]]
shape array : (2, 3)
jumlah elemen array : 6


Fungsi Statistik 
mean() sum() min() max()

In [59]:
array = np.array([1,2,3,4,5])

print(f"array : {array}")

print(f"rata rata array : {np.mean(array)}")
print(f"jumlah array : {np.sum(array)}")
print(f"nilai minimum : {np.min(array)}")
print(f"nilai maksimum : {np.max(array)}")
print(f"nilai median : {np.median(array)}")
print(f"nilai standar deviasi : {np.std(array)}")
print(f"nilai variansi : {np.var(array)}")
print(f"nilai kuartil : {np.percentile(array, 50)}")
print(f"nilai kuartil : {np.percentile(array, 50)}")


array : [1 2 3 4 5]
rata rata array : 3.0
jumlah array : 15
nilai minimum : 1
nilai maksimum : 5
nilai median : 3.0
nilai standar deviasi : 1.4142135623730951
nilai variansi : 2.0
nilai kuartil : 3.0
nilai kuartil : 3.0


# Distribusi probabilitas
menggambarkan bagaimana data tersebar numpy menyediakan berbagai fungsi membuat array sesuai distribusi tertentu

Distribusi Normal 
memiliki penyebaran data yang simetris dan sering di gunakan dalam statistik

sintaks np.random.normal(loc,scale,size)
loc: mean (rata-rata) distribusi (default 0)
scale: standar deviasi distribusi ( default 1 )
size : ukuran array

In [70]:
array_normal = np.random.normal(loc=7,scale=1, size=5)
print(array_normal)
print(array_normal.mean())

[6.15754914 6.44049156 6.59631311 6.4168066  8.74803235]
6.871838552707738


Distribusi Uniform
memiliki probabilitas yang sama untuk semua nilai dalam rentang tertentu 

sintaks : np.random.uniform(low, high,size)

low : batas bawah (default 0 )
hight : batas atas (default 1)
size ukuran array

In [80]:
array_uniform = np.random.uniform(low=0, high=10, size=5)
print(array_uniform)
print(array_uniform.mean())

[4.4325362  0.11907206 8.55078689 9.08487199 1.96613917]
4.830681260632714
